# Generated by Django 4.0.5 on 2023-04-07 08:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=users.models.upload_avatar_to, verbose_name='profile picture'),
        ),
    ]
