# Generated by Django 4.0.5 on 2023-05-09 08:09

import core_app.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filemanager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileStorageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField(default=5368709120, help_text='Byte')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_public', models.FileField(blank=True, null=True, upload_to=filemanager.models.user_directory_path)),
                ('file_private', models.FileField(blank=True, null=True, storage=core_app.storage_backends.PrivateMediaStorage(), upload_to=filemanager.models.user_directory_path)),
                ('storage_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20, verbose_name='Upload File Type')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filemanager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
